elasticsearch:
  ip: 127.0.0.1
  port: 9300
  pool: 5
  cluster:
    name: pxc


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house-search
    username: root
    password: 935377012
    driver-class-name: com.mysql.jdbc.Driver
  elasticsearch:
    jest.uris: http://127.0.0.1:9200


