spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house-search?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 935377012
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: yuqiao
      cluster-nodes: 132.232.75.97:9300
qq:
  appid: 101512317
  appkey: b8a753e58978a50d269120ba163b9047
mybatis:
  mapper-locations: classpath:yuqiao/housesearch/mapper/**.xml
